default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  database: <%= ENV['DATABASE_NAME'] || 'todo_app_development' %>

development:
  <<: *default

test:
  <<: *default
  database: todo_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
