name: Build and Deploy to AKS
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: todoappacr.azurecr.io
          username: ${{ secrets.SERVICE_PRINCIPAL }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: todoappacr.azurecr.io/todo-app:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: todoAppResourceGroup
          cluster-name: todoAppCluster

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            kube/deployment.yml
            kube/service.yml
          images: todoappacr.azurecr.io/todo-app:latest
